### ISSUE TITLE
How to add custom header like cookies or referer in CLI version?

### ISSUE THREAD

**Issue by lamualfa** [clitic/vsd#1]

**Comment by clitic** [comment]
Currently, you cannot add header like cookies. I think it could be supported by using reqwest library [Jar](https://docs.rs/reqwest/latest/reqwest/cookie/struct.Jar.html) struct. I would try to implement this feature in the next commit.

**Comment by lamualfa** [comment]
@clitic how about the header referer? several sites use it to protect illegal request outside their website.

**Comment by clitic** [comment]
@lamualfa reqwest library automatically set `Refer` header [see here](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.referer).

You can still override it by using `--header` flag. example `--header Referer https://www.google.com/`
It should work for media playlists.
