### ISSUE TITLE
Download video from site that requires login

### ISSUE THREAD

**Issue by karpiu** [clitic/vsd#10]
I try to add session cookie through headers, but it does not work:

```
vsd save https://<some site>.m3u8 -o <output>.mp4 --header cookie <a value I copy from request header after login into the site>
error: Couldn't parse https://<some site>.m3u8 playlist.
```

I would like to know at least if this is because of Unauthorized response from server, but I don't see any `--verbose` option.

Also note that doing normal http content scraping I use with ruby `open-uri` and `nokogiri` works on that site when I pass the same header as in the command above to my scripts. Also I don't want to use `collect` or `capture` and manually login every time, because there are hundreds of videos and I would rather download them using a script. Any ideas?

**Comment by clitic** [comment]
@karpiu I am currently working on [playlist](https://github.com/clitic/vsd/tree/playlist) branch which has many breaking changes. I need some time add `--verbose` like feature.

If you can replicate the request using curl and send me the response maybe I can help you.

If you think cookies are the only thing which are causing it fail then try to use `--cookies` flag and supply `set-cookie` header value for every url you visited to get cookies.

```
--cookies <COOKIES> <URL>
          Enable cookie store and fill it with some existing cookies. Example `--cookies "foo=bar;
          Domain=yolo.local" https://yolo.local`. This option can be used multiple times
```

**Comment by karpiu** [comment]
@clitic Update: I managed to solve my problem by using your previous work https://github.com/clitic/vsdownload

I used option `--headers` with a json file that looks more or less like this:

```
{
    "accept": "text/html, application/xhtml+xml",
    "accept-language": "en-US,en;q=0.9,pl;q=0.8",
    "sec-ch-ua": "\"Chromium\";v=\"109\", \"Not_A Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Linux\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "turbo-frame": "episode_video",
    "cookie": "<the most important value containing session cookies>",
    "Referer": "<hidden>",
    "Referrer-Policy": "strict-origin-when-cross-origin"
}
```
This is just copied request header from my browser. And it actually works. It's a shame there is no client option to pre-select quality (only maximum, when in my case I need minimum), but I will take care of this myself.

This shows that there is something wrong with how your current project handles request headers. Maybe you should take a look sometime.

**Comment by karpiu** [comment]
Added min-quality option to vsdownload in my fork: https://github.com/karpiu/vsdownload in case someone has the same problem and google sends him to this thread.

**Comment by clitic** [comment]
@karpiu All bugs are fixed. Now you can use `--cookie` flag and supply it `document.cookie` value and it should work as expected. Also, based on your suggestion I have added `lowest`/`min`  quality options.

**Comment by karpiu** [comment]
Thanks @clitic for your work. Cheers
