### ISSUE TITLE
Navigate failed: net::ERR_ABORTED

### ISSUE THREAD

**Issue by wabiloo** [clitic/vsd#12]
Hi,

I am trying to use the pre-compiled release on my Mac (with macOS 13.1), to download an HLS stream.

Chrome opens briefly and then immediately I get `error: Navigate failed: net::ERR_ABORTED` 

```
> ./vsd collect https://test-streams.mux.dev/x36xhzz/url_6/193039199_mp4_h264_aac_hq_7.m3u8
Chrome will launch with a window for 3 minutes.
error: Navigate failed: net::ERR_ABORTED
```

I also tried with `--headless`, but with no success

```
> ➜  ./vsd collect https://test-streams.mux.dev/x36xhzz/url_6/193039199_mp4_h264_aac_hq_7.m3u8 --headless
Chrome will launch without a window for 3 minutes.
error: The event waited for never came
```

**Comment by wabiloo** [comment]
Ah, I think I misunderstood what this tool does.
It seems to expect a web player to play the stream, and then captures the files.

So, I did that using a test player with that stream, and `vsd` downloaded just the `m3u8`, not the `ts` segments.
Is that as expected?

What I'm trying to do is download all files that are part of the stream (all qualities)...

**Comment by clitic** [comment]
@wabiloo `collect` sub command doesn't download `.ts` files. You can use [Stream Recorder Add On](https://chrome.google.com/webstore/detail/stream-recorder-download/iogidnfllpdhagebkblkgbfijkbkjdmm) for that puropse. The main purpose of collect sub command is to capture url and response for playlist which then can be used by `save` sub command to download all segments.
