### ISSUE TITLE
An Actual Apk App 

### ISSUE THREAD

**Issue by Sfixyt** [clitic/vsd#15]
Can you build an easy Android App that can download provided m3u8 hls links and save them as mp4 or even better as mkv x265 to save disk space and

**Comment by clitic** [comment]
This project doesn't aim to provide an android app but you can use vsd inside [termux](https://github.com/clitic/vsd/blob/main/vsd/docs/running-on-android.md) on android. Then re-encode downloaded stream to x256 mkv using ffmpeg.
