### ISSUE TITLE
Regarding M3U8 Playlist Generation

### ISSUE THREAD

**Issue by ameyjir** [clitic/vsd#17]
**Description:**
I aimed to "Clone" or download the segments and playlist files as-is without merging them. However, VSD currently downloads and merges the video file into an .mp4 format before creating the HLS segments and playlist file. This approach has led to an issue.

**Issue:**
I have encountered an issue with the current behaviour of VSD (Video Stream Downloader) when generating M3U8 playlists using the `-o` option with a `.m3u8` file extension. The generated playlist does not list all the individual segment files as expected.

**Reproduction Steps:**
1. Use VSD with the `-o` option to generate an M3U8 playlist with a `.m3u8` extension, as follows:
   ```
   vsd save <URL> -o playlist.m3u8 -q highest
   ```

2. Check the generated playlist file (`playlist.m3u8`) to observe the listed segments.

**Current Behaviour:**
The generated playlist might not list all individual segments correctly, and the media sequence numbers may not align with the actual filenames of the segments. Possibly only last three segments may get listed in playlist

**Expected Behaviour:**
When generating an M3U8 playlist using the `-o` option with a `.m3u8` extension, it is expected that the playlist should accurately list all the individual segment files and align the media sequence numbers with the actual filenames of the segments.

**Environment:**
- VSD Version: 0.2.5
- Operating System: Windows 10

**Solution:**
I have successfully addressed this issue by using the `-hls_time` , `-hls_list_size` & `-start_number`  option with the `ffmpeg` command when generating the M3U8 playlist, command:
```
ffmpeg -i video.mp4 -c:v copy -c:a copy -hls_time <segment_duration> -hls_list_size <list_size> -start_number <start_sequence_number> playlist.m3u8
```

Just for reference this was the command I used:

```
ffmpeg -i video.mp4 -c:v copy -c:a copy -hls_time 3 -hls_list_size 2000 -start_number 0 video.m3u8
```
Specifying these parameters along with sequence number is crucial for proper playlist generation. The "video.m3u8" should be at the end after all the options.

**Comment by ameyjir** [comment]
Hi, hope you're doing well. I'd like to inquire about the status of the `--no-merge` flag request. 
Thanks.

**Comment by clitic** [comment]
Sorry, I forgot about this feature request. For now I have created a new issue for this. I will add this feature most probably tommorow and update you.

**Comment by clitic** [comment]
@ameyjir I have added `--no-merge` flag (81db905). It still needs some more work but you can try it. Also, note that for now only segments are saved not playlist and segments are arranged like 0.ts, 1.ts, 2.ts, ... You can suggest me more improvements and I will try to implement them.
