### ISSUE TITLE
error when using the `vsd --capture` behind cloudflare warp connection

### ISSUE THREAD

**Issue by lamualfa** [clitic/vsd#2]
# description
specific sites are blocked in my country. i need to use [cloudflare warp](https://1.1.1.1/) to unblock the targeted sites. but the problem occurs when using the vsd within the cloudflare warp connection.

## command
```bash
vsd https://www.youtube.com/watch?v=vT1HI_-dJwA --capture
```

> command `vsd https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8 -o video.mp4` working perfectly. the problems only occur in the capture & collect feature.

## error
![image](https://user-images.githubusercontent.com/39755201/177609874-fc3b9411-0569-476e-bca2-d5ed12c9f85a.png)

# tech stack

## vsd
![image](https://user-images.githubusercontent.com/39755201/177609757-b511e753-4f10-47a9-b1d3-e10112bb663e.png)

## google-chrome
![image](https://user-images.githubusercontent.com/39755201/177609605-303a1db4-5a80-4016-bb02-738c7ebe60f7.png)

## ffmpeg
![image](https://user-images.githubusercontent.com/39755201/177609683-7773512b-35f6-4e6a-a9e3-988f55b411d2.png)

## cargo
![image](https://user-images.githubusercontent.com/39755201/177610601-d9704174-c768-4601-a292-dd15aad2818f.png)

## os
wsl 2 with ubuntu 20 distro within windows 11

# another

## also, gui version of the google-chrome usually works within wsl 2
![image](https://user-images.githubusercontent.com/39755201/177610846-e1ebaf27-ff85-4889-83c0-b5cccfbfc6a8.png)

**Comment by clitic** [comment]
`--capture`and `--collect` works on same principle. So if collect fails capture will also fail and vice versa. For `--collect` flag I mentioned the [reason](https://github.com/clitic/vsd/issues/3#issuecomment-1176562528) for it's fail.

**Comment by lamualfa** [comment]
@clitic sometimes i got the error, and sometimes it's just worked. I'm a little confused about what's the reason. for now, i'll close this issue. i am not sure the cause comes from cloudflare warp. thanks.
