### ISSUE TITLE
Unable to pass cookies 

### ISSUE THREAD

**Issue by Nomanali3468** [clitic/vsd#22]
GET /live_record_g/STAR_LIFE_1494_250_320x240_v1_FMP4/record_5215226.m3u8 HTTP/1.1
User-Agent: Mozilla/5.0 (Linux; Android 12) StarTimesON/6.8-1
Accept: */*
Range: bytes=0-
Connection: close
Host: cloudflare-video.gslb.startimestv.com
Cookie: CloudFront-Signature=AbrjlHHK2m1TxUqCncwe17wljFVDwc8Yga~QJIxx8z3YQJ8Wwr4dmg5OiuGV29KWyrgbYX05jSrGGkEXxyXg4KBMIj2SHxR9~UgCxAWagLWCv0eU3qagsomPYXuLmhctJZjOgnDQ3AQ4mGruNNY5c~HTgkiGCZCYg0NwiJAnEJj9lbn-yH93XZ8hJxLUmJKthTko9V09sd3uCSWcc3MnU1ueFvzQd5lHNwoIRP~nq~ZycweekmwSmx9sZFu~SvLg8rHXrcxbjK-pDIt6cE6GepGUNasRK0UeJvfk-tXcwxSCVcxlmDOjeNIzjASPwv3qaJ318HcjLu0JiVL8F3C70Q__;CloudFront-Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHA6Ly8qLnN0YXJ0aW1lc3R2LmNvbS9saXZlX3JlY29yKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NjIzNjc3OX19fV19;CloudFront-Key-Pair-Id=APKAIPKYIDIQPHMZ2WKA

I have tried to pass cookies but still not working got error

vsd save --set-cookie "CloudFront-Signature=AbrjlHHK2m1TxUqCncwe17wljFVDwc8Yga~QJIxx8z3YQJ8Wwr4dmg5OiuGV29KWyrgbYX05jSrGGkEXxyXg4KBMIj2SHxR9~UgCxAWagLWCv0eU3qagsomPYXuLmhctJZjOgnDQ3AQ4mGruNNY5c~HTgkiGCZCYg0NwiJAnEJj9lbn-yH93XZ8hJxLUmJKthTko9V09sd3uCSWcc3MnU1ueFvzQd5lHNwoIRP~nq~ZycweekmwSmx9sZFu~SvLg8rHXrcxbjK-pDIt6cE6GepGUNasRK0UeJvfk-tXcwxSCVcxlmDOjeNIzjASPwv3qaJ318HcjLu0JiVL8F3C70Q__;CloudFront-Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHA6Ly8qLnN0YXJ0aW1lc3R2LmNvbS9saXZlX3JlY29yKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NjIzNjc3OX19fV19;CloudFront-Key-Pair-Id=APKAIPKYIDIQPHMZ2WKA" "http://cloudflare-video.gslb.startimestv.com/live_record_g/STAR_LIFE_1494_250_320x240_v1_FMP4/record_5215226.m3u8" output_file.mp4                                            error: builder error: relative URL without a  #base

**Comment by clitic** [comment]
You should pass `Cookie` header value with `--cookies` flag.

```bash
vsd save http://cloudflare-video.gslb.startimestv.com/live_record_g/STAR_LIFE_1494_250_320x240_v1_FMP4/record_5215226.m3u8 --cookies "CloudFront-Signature=AbrjlHHK2m1TxUqCncwe17wljFVDwc8YgaQJIxx8z3YQJ8Wwr4dmg5OiuGV29KWyrgbYX05jSrGGkEXxyXg4KBMIj2SHxR9UgCxAWagLWCv0eU3qagsomPYXuLmhctJZjOgnDQ3AQ4mGruNNY5cHTgkiGCZCYg0NwiJAnEJj9lbn-yH93XZ8hJxLUmJKthTko9V09sd3uCSWcc3MnU1ueFvzQd5lHNwoIRPnqZycweekmwSmx9sZFuSvLg8rHXrcxbjK-pDIt6cE6GepGUNasRK0UeJvfk-tXcwxSCVcxlmDOjeNIzjASPwv3qaJ318HcjLu0JiVL8F3C70Q__;CloudFront-Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHA6Ly8qLnN0YXJ0aW1lc3R2LmNvbS9saXZlX3JlY29yKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NjIzNjc3OX19fV19;CloudFront-Key-Pair-Id=APKAIPKYIDIQPHMZ2WKA"
```

If vsd still gives error then try to get playlist response using curl.

```bash
curl http://cloudflare-video.gslb.startimestv.com/live_record_g/STAR_LIFE_1494_250_320x240_v1_FMP4/record_5215226.m3u8 --header "Cookie: CloudFront-Signature=AbrjlHHK2m1TxUqCncwe17wljFVDwc8YgaQJIxx8z3YQJ8Wwr4dmg5OiuGV29KWyrgbYX05jSrGGkEXxyXg4KBMIj2SHxR9UgCxAWagLWCv0eU3qagsomPYXuLmhctJZjOgnDQ3AQ4mGruNNY5cHTgkiGCZCYg0NwiJAnEJj9lbn-yH93XZ8hJxLUmJKthTko9V09sd3uCSWcc3MnU1ueFvzQd5lHNwoIRPnqZycweekmwSmx9sZFuSvLg8rHXrcxbjK-pDIt6cE6GepGUNasRK0UeJvfk-tXcwxSCVcxlmDOjeNIzjASPwv3qaJ318HcjLu0JiVL8F3C70Q__;CloudFront-Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHA6Ly8qLnN0YXJ0aW1lc3R2LmNvbS9saXZlX3JlY29yKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NjIzNjc3OX19fV19;CloudFront-Key-Pair-Id=APKAIPKYIDIQPHMZ2WKA"
```

Now, if playlist is displayed on your terminal and vsd command still gives an error. It means that there is a bug in vsd (then send me your console log). If it doesn't then there is no bug. From my side I have checked that vsd correctly handles cookies. It could be some other bug. Please send me working playlist link.

**Comment by Nomanali3468** [comment]
Here is the log

~ $ ./vsd save http://cloudflare-video.gslb.startimestv.com/live_record_g/STAR_LIFE_1494_250_320x240_v1_FMP4/record_5220088.m3u8 --cookies "CloudFront-Signature=VbTTjaSySDeCsLEyCqJFJXDGm~XGwFkhzSWOB~1vzi3vt-5F32rND-zjweu~4LBmWBK-sJFkQCkU~MqQWOsaX8O0PdgHdLl1x20rGeVvmaw~e9nZQa~2oiOTScRSqyFY~gM-nm91V4-Jys7iBjXacXLMdQTnmDJ2mVsbZIic-mTbyMpBVRg7CRnVAUkePWMMl4Z3kng0H8LImPnJ2BXQyfcAsDY~GrkBGPR-QICBPWIwlYABENrB5VgoE2eUzt1vF4U27FEG~G79qNXHaEtmDuNxl0zwQF3bTe91FcUW~lB0fz9sCprgmjxKwPndog2~W~LxAqrVuTTz~7ayDa2KKw__;CloudFront-Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHA6Ly8qLnN0YXJ0aW1lc3R2LmNvbS9saXZlX3JlY29yKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NjQ4Mzc5OX19fV19;CloudFront-Key-Pair-Id=APKAIPKYIDIQPHMZ2WKA"
   Scraping website for DASH and HLS playlists
error: No links found on website source.

TRY THIS: Consider using capture subcommand and then run the save subcommand with same arguments by replacing the INPUT with captured url.

Suppose first command captures https://streaming.site/video_001/master.m3u8
$ vsd capture http://cloudflare-video.gslb.startimestv.com/live_record_g/STAR_LIFE_1494_250_320x240_v1_FMP4/record_5220088.m3u8
$ vsd save https://streaming.site/video_001/master.m3u8

OR THIS: Consider using collect subcommand and then run save subcommand with saved playlist file as INPUT.

Suppose first command saves master.m3u8
$ vsd collect --build http://cloudflare-video.gslb.startimestv.com/live_record_g/STAR_LIFE_1494_250_320x240_v1_FMP4/record_5220088.m3u8
$ vsd save master.m3u8

**Comment by Nomanali3468** [comment]
Curl Response:

~ $ curl http://cloudflare-video.gslb.startimestv.com/live_record_g/STAR_LIFE_1494_250_320x240_v1_FMP4/record_5220088.m3u8 --header "Cookie:CloudFront-Signature=VbTTjaSySDeCsLEyCqJFJXDGm~XGwFkhzSWOB~1vzi3vt-5F32rND-zjweu~4LBmWBK-sJFkQCkU~MqQWOsaX8O0PdgHdLl1x20rGeVvmaw~e9nZQa~2oiOTScRSqyFY~gM-nm91V4-Jys7iBjXacXLMdQTnmDJ2mVsbZIic-mTbyMpBVRg7CRnVAUkePWMMl4Z3kng0H8LImPnJ2BXQyfcAsDY~GrkBGPR-QICBPWIwlYABENrB5VgoE2eUzt1vF4U27FEG~G79qNXHaEtmDuNxl0zwQF3bTe91FcUW~lB0fz9sCprgmjxKwPndog2~W~LxAqrVuTTz~7ayDa2KKw__;CloudFront-Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHA6Ly8qLnN0YXJ0aW1lc3R2LmNvbS9saXZlX3JlY29yKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NjQ4Mzc5OX19fV19;CloudFront-Key-Pair-Id=APKAIPKYIDIQPHMZ2WKA"
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:12
#EXT-X-MEDIA-SEQUENCE:2807601
#EXT-X-MAP:URI="init_2654425.mp4",STAR-INIT-DATA="eJytUr9PwkAUfteiojHCAIbBAY2LJsbgr4SEoVEHBhdjxJg4WLliCS1teqX+mFjdHNTZ0ejoX2Di7H/g7mJkdNDguwNCKUIw8aV533v3vt69d98BQKLgntlFZq0CSIC4ZtorKYDQjWlZHgAYpqdT6DD5TQARX9tIJyuYK9DXJPzhznXUEsYHbkmcKffZXayRP59LNk1aVDFImjQ4V26G+91nkSzo1HBaFWZVyn7mDuY0q5apoQnOh1ksFxCjzOzYdJY21qeooxV87Y1XHCPZjB+Ze2QgHjOXUR9nD4VQu0aSINpuFZY1RhkP5Gq1OoO0EGJMiYtiJs39EK5I8fAwApFEi67LfC1izvK+PIb5eee9cE7eaqfSUh+dJOhlA+hE7u8foCaKL711ygj/m05ekWp+Zg5zq60TOWvqFPMaOvlbGEArkm5q9R7Q6lXXvFSPMYEoOFIWg2wvRpcl6nX0J7qX3yDkEMPLxuA1+Pr+/ASIyEncJaGQcVKvc4LMGTL/MtdXo9NYnF8nJFC5HQtHJvf3y1uLE3qYrwh3qvCHM7JJntjc9gWeErVVZiOGoKHsP7wYyJqedoqYdB2BrWsIXoW/LgXrPwoei1E="
#EXT-X-M3U8-OPTIMIZE:VOD=1,START_INDEX=2807601.m4s,END_INDEX=2807750.m4s,INDEX_COUNT=150,SEGMENT_DURATION=12,SEGMENT_TOTAL_DURATION=1800.0,INITMP4_COUNT=1,MAX_OFFSET=0.0,LAST_SEGMENT_DURATION=12.0
#EXTINF:12.0
2807601.m4s

**Comment by Nomanali3468** [comment]
I can't provide working playlist due to cookies expiry issue after 30 minutes cookies are expiring
