### ISSUE TITLE
Cannot decode PSSH box data as valid widevine data.

### ISSUE THREAD

**Issue by mohamedhani1** [clitic/vsd#23]
I try to download mpd url but I get this error

error: Cannot decode PSSH box data as valid widevine data.

DecodeError {
    description: "invalid wire type: Varint (expected LengthDelimited)",
    stack: [
        (
            "WidevinePsshData",
            "key_ids",
        ),
    ],
}.

**Comment by clitic** [comment]
Your playlist might contain protected streams. Some encryption information is saved inside init segment which vsd tries to parse but here it fails to decode it. From my side I have checked that it correctly parses mp4's PSSH box data. In your case init segment might be corrupted.
