### ISSUE TITLE
Detect ffmpeg

### ISSUE THREAD

**Issue by psociety** [clitic/vsd#27]
1. I place the url
2. It lets me choose the quality
3. Starts downloading it

 FUCKING FINALLY. No retarded software that downloads a single `.ts` and calls it a day. Or only downloads the audio, or the worst possible quality.
THANK YOU FOR CREATING SUCH USEFUL APPLICATION!!!

Just a single suggestion: Maybe the command should check for `ffmpeg` before starting the downoad if it knows it will needed?
Just to avoid cases like this:
```
vsd save https://myfile.m3u8 -o video.mp4
• Select streams to download · 1080p 8.81 MiB/s (codecs: avc1.640028,mp4a.40.2, frame_rate: 25) | language: spa | language: spa
 Processing subtitles stream language: spa
Downloading stream to myfile_m3u8.vtt
 Downloaded stream successfully
79.16 KiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 9/9 • 00:01 > 00:00 • 7.61 SEG/s
 Processing video stream 1080p 8.81 MiB/s (codecs: avc1.640028,mp4a.40.2, frame_rate: 25)
Downloading stream to myfile_m3u8.ts
 Downloaded stream successfully
 Processing audio stream language: spa
Downloading stream to myfile_m3u8.aac
 Downloaded stream successfully
2.20 / 2.20 GiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.00% • 520/520 • 02:41 > 00:00 • 3.21 SEG/s • 7.92 MiB/s
  Executing ffmpeg -i myfile_m3u8.ts -i myfile_m3u8.aac -i myfile_m3u8.vtt -c copy -c:s mov_text -map 0 -map 1 -map 2 -metadata:s:a:0 language=spa -metadata:s:s:0 language=spa video.mp4
error: program not found
```

It downloaded the whole file just for it to end up failing.

**Comment by clitic** [comment]
@psociety  Thanks for your suggestion. I will definitely add feature to detect ffmpeg.

After downloading streams ffmpeg is used to merge streams only, nothing else is done after that. So you can execute this command manually in order to obtain final stream and delete downloaded ts files.

```
ffmpeg -i myfile_m3u8.ts -i myfile_m3u8.aac -i myfile_m3u8.vtt -c copy -c:s mov_text -map 0 -map 1 -map 2 -metadata:s:a:0 language=spa -metadata:s:s:0 language=spa video.mp4
```
