### ISSUE TITLE
Support for ARM64 Macos

### ISSUE THREAD

**Issue by ar5hil** [clitic/vsd#28]
there are no binaries for arm64, could you please add them, if possible direct installation through [brew](https://brew.sh/)

**Comment by clitic** [comment]
Arm64 for Macos is already available [here](https://github.com/clitic/vsd/releases/download/v0.3.0/vsd-v0.3.0-aarch64-apple-darwin.tar.xz). I don't know how to upload vsd to homebrew so I can't do this.
