### ISSUE TITLE
what's going to do after the chrome window opens in collect mode?

### ISSUE THREAD

**Issue by lamualfa** [clitic/vsd#3]
# description

how to download the video after the chrome window is opened? i've played the video and opened the dev tools, and nothing happened. am i missing a step?

![image](https://user-images.githubusercontent.com/39755201/177612639-f0cf9662-d95e-4175-b81c-42a6e5cea95e.png)

**Comment by clitic** [comment]
You are not missing any steps. Running with `--collect` flag saves a local .m3u8 file when the video starts playing. This saved .m3u8 file then can be passed to vsd directly.

As you can see in the terminal last printed line says `Using COMMAN method for collection`. This means vsd doesn't have a method for collecting and capturing links from that site but it will try to do so. Currently, there is no method for collecting videos from YouTube.

> YouTube links aren't supported yet.

You can try using `--collect` flag with other websites and check if that works.

**Comment by lamualfa** [comment]
yosh, it's worked when using the `--capture` method, but not with `--collect`. i have no idea how `--collect` works and how to use it properly.

thanks.

![image](https://user-images.githubusercontent.com/39755201/177698889-6c668452-6ff4-41de-9061-b99e90d8f4a9.png)
