### ISSUE TITLE
Found Scraped URL Misspelled&Incomplete

### ISSUE THREAD

**Issue by MuhammadBayiz** [clitic/vsd#31]
Downloading a video from https://www.kanald.com.tr/amp/yalan/bolumler/yalan-2-bolum

Using the command 
`vsd save https://www.kanald.com.tr/amp/yalan/bolumler/yalan-2-bolum`
Finds a m3u8 url but misspelled like so
`https://kanaldvod.duhnet.tv/https://kanaldvod.duhnet.tv/hls/r/3D/yalan2blm/yalan2blm.smil/playlist.m3u8
`
The correct url is
`https://kanaldvod.duhnet.tv/hls/r/3D/yalan2blm/yalan2blm.smil/playlist.m3u8`

The base url is duplicated.

**Comment by MuhammadBayiz** [comment]
The other one that's incomplete is
When i try to download from NowTV with this command:
`vsd save https://www.nowtv.com.tr/Son-Yaz/bolum/13`
The found url is:
`https://nowtv-vod.ercdn.net/Son-Yaz/bolumler/13/PDT1SONYAZ13HDRTUK7YASVEUZERISIDDETOLUMSUZDAVRANISLAR5M.smil/playlist.m3u8`
But the correct one is:
`https://nowtv-vod.ercdn.net/Son-Yaz/bolumler/13/PDT1SONYAZ13HDRTUK7YASVEUZERISIDDETOLUMSUZDAVRANISLAR5M.smil/playlist.m3u8?st=V8d-8E_2wN0VjI2Y-IShPQ&e=1719085331`

So the url is missing some strings
By doing a curl on the webpage we get 
`source: 'https://nowtv-vod.ercdn.net/Son-Yaz/bolumler/13/PDT1SONYAZ13HDRTUK7YASVEUZERISIDDETOLUMSUZDAVRANISLAR5M.smil/playlist.m3u8?st=V8d-8E_2wN0VjI2Y-IShPQ&e=1719085331',` in line **3447** which shows the real m3u8 url.

This one i suspect that it might be that vsd is matching the url that ends with m3u8 rather than getting the full url

**Comment by clitic** [comment]
Baseurl bug is fixed with version 0.3.1.

vsd is meant for downloading hls playsit by their link and cookies but scarper part was written to extract these links. This scraper is not meant to be used even though it is given.  My plan is to support various sites like youtube-dl but that functionality is not implemented till now.

Meanwhile you can just use

```
vsd save "https://nowtv-vod.ercdn.net/Son-Yaz/bolumler/13/PDT1SONYAZ13HDRTUK7YASVEUZERISIDDETOLUMSUZDAVRANISLAR5M.smil/playlist.m3u8?st=V8d-8E_2wN0VjI2Y-IShPQ&e=1719085331"
```

I do consider your suggestion on parsing url queries when scraper founds a link. I will try to implement it soon.

**Comment by MuhammadBayiz** [comment]
The baseurl still shows duplicate in the new version 0.3.1
```
~ $ ./vsd save https://embed.kanald.com.tr/embed/665dbf56aa22481e27692122
   Scraping website for DASH and HLS playlists
      Found https://kanaldvod.duhnet.tv/https://kanaldvod.duhnet.tv/hls/r/3D/yalan2blm/yalan2blm.smil/playlist.m3u8
error: couldn't determine playlist type, only DASH and HLS playlists are supported.
```

Using _vsd-0.3.1-x86_64-unknown-linux-musl.tar.xz_ binary, can you check on the above link see if the baseurl is fixed? 

The url scraper is my favorite tool it makes a lot of things easier like i can just pass through a url in a matter of seconds without needing to go for extra steps to extract the url myself. So thank you very much for considering my suggestion.

**Comment by clitic** [comment]
I will re-test everything.

**Comment by clitic** [comment]
All bugs have been fixed you can check the latest commit.

**Comment by MuhammadBayiz** [comment]
it works very smoothly now, thanks
