### ISSUE TITLE
v0.3.1 notified the new release of v0.3.0

### ISSUE THREAD

**Issue by lsy223622** [clitic/vsd#32]
![image](https://github.com/clitic/vsd/assets/57913213/537919ec-425b-4520-8838-ca4eb8e9f526)

**Comment by clitic** [comment]
This should be fixed in next release. Thanks for reporting.

**Comment by clitic** [comment]
All bugs have been fixed you can check the latest commit.

**Comment by clitic** [comment]
@lsy223622 vsd [0.3.2](https://github.com/clitic/vsd/releases/tag/0.3.2) released
