### ISSUE TITLE
Suggestion: reduce error message

### ISSUE THREAD

**Issue by lsy223622** [clitic/vsd#33]
In some situations some segments in a playlist may be broken or a poor network connection can lead to quite a lot lines of error messages, making the output noisy and unclear.
In my case of usage, lost of a few seconds in an hour is acceptable, and actually most of those segments are successfully downloaded after one or more retries. So keeping the output clean is safe and comforting.
I suggest using a number or a small graphic to indicate the success/failure status. And detailed information can be written to a log file.
Or maybe you can just add a command option to turn off those non-critical error messages. Then current behaviour won't be changed, yet gives an alternative choice.
Thanks again for your program and kind updates.
![image](https://github.com/clitic/vsd/assets/57913213/f3ff15de-fbbe-4d9f-86be-a49d676facac)

**Comment by nxhda** [comment]
Failed to decrypt video
