### ISSUE TITLE
Request: lib target for programmatic use

### ISSUE THREAD

**Issue by pimlie** [clitic/vsd#34]
Would you maybe be interested in adding support to use vsd as a library?

A use case for this could f.e. be to mux the HLS/DASH stream of a video post in https://github.com/redlib-org/redlib so that users can quickly download hq videos with audio :)

**Comment by clitic** [comment]
Of course, that should be great. I would work on that soon. Maybe you can suggest some features for lib api.

**Comment by clitic** [comment]
Yes, it relies on ffmpeg for now but you can use libav too.
