### ISSUE TITLE
After download merge won’t work

### ISSUE THREAD

**Issue by DANIEL120321** [clitic/vsd#39]
getting some errors after downloading. 

22.18 / 22 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.00% • 42/42 • 00:02 > 00:00 • 18.87 SEG/s • 10.80 MiB/s
  Executing ffmpeg -i vsd_video_Manifest_ism.mp4 -i vsd_audio_Manifest_ism.mp4 -c copy vid.mp4
   Deleting vsd_video_Manifest_ism.mp4
   Deleting vsd_audio_Manifest_ism.mp4
'bitrate' is not recognized as an internal or external command,
operable program or batch file.
'id' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file 160000000.

**Comment by clitic** [comment]
This not a error related to vsd.
