### ISSUE TITLE
Can collect function passing the headers data?

### ISSUE THREAD

**Issue by lamualfa** [clitic/vsd#4]
The collect function only passings the `intercepted.request.url` data. Is it possible to include the headers data from `intercepted.request.headers`? Several sites may use cookies to distinguish suspicious requests.

https://github.com/clitic/vsd/blob/d234217244b3e333cd08fb4498248313b81a4ea0/src/chrome.rs#L149

**References**

- https://docs.rs/headless_chrome/latest/headless_chrome/protocol/network/struct.Request.html#structfield.headers

**Comment by clitic** [comment]
I will implement it soon.
