### ISSUE TITLE
Support for canceling the captured requests

### ISSUE THREAD

**Issue by lamualfa** [clitic/vsd#5]
Several servers, like [akamai](https://www.akamai.com/), will block all requests after the first request. This problem will make the second request from `vsd` be blocked (_the first request happens on the website or browser, and the second request happens inside the `vsd`_).

Can we add a new parameter like `--block-captured-requests` to tell `vsd` to don't let the captured requests continue/pass to prevent duplicate requests?

https://github.com/clitic/vsd/blob/d234217244b3e333cd08fb4498248313b81a4ea0/src/chrome.rs#L152

I can make a PR for this simple request (still learning rust😭. come from javascript & golang).

**Comment by clitic** [comment]
I think if we do not continue the request. Servers won't send next request. We can still create a function like `--block-captured-requests` but it might not work. Feel free to create a PR.

**Comment by lamualfa** [comment]
> I think if we do not continue the request. Servers won't send next request. We can still create a function like `--block-captured-requests` but it might not work. Feel free to create a PR.

Yeah. Blocking a request may break the next web process. This solution will fit if the website only calls a master or index `m3u8` file once, and the rest download process will continue by `vsd`.

**Comment by clitic** [comment]
> after we get the master m3u8 file, we can ignore the entire process in the website.

We can continue request if captured link is .vtt. And if .m3u8 or .mpd file is captured then we can block request.

**Comment by lamualfa** [comment]
> I think it's possible.

or another solution is to reuse the request's response that the browser does to master m3u8 file. So we don't need to pass URL and headers again. Also `vsd` don't need to download the master m3u8 again.

But I don't think the `headless_chrome` interception support this case.

**Comment by clitic** [comment]
@lamualfa thanks for your suggestion. I found out headless_chrome [enable_response_handling](https://docs.rs/headless_chrome/latest/headless_chrome/browser/tab/struct.Tab.html#method.enable_response_handling) method which lets you to get response body of request made by chrome. So I have implemented it, you can use this [windows binary](https://github.com/clitic/vsd/releases/download/v0.1.3.dev/vsd-v0.1.3-dev-x86_64-pc-windows-msvc.zip) to test it out.

**Comment by lamualfa** [comment]
@clitic I've tested the new binary of `vsd` version, and it works very well without any additional configurations. Thanks.

**Comment by lamualfa** [comment]
@clitic I think we can implement a new recording feature to record a live stream. Technically grab all `.ts` responses the browser makes and process them to a `.mp4` file after the recording stops.

It's just an idea. You don't have to implement it soon.

**Comment by lamualfa** [comment]
The idea comes from [Stream Recorder Add On](https://chrome.google.com/webstore/detail/stream-recorder-download/iogidnfllpdhagebkblkgbfijkbkjdmm)'s recording feature implementation.

**Comment by clitic** [comment]
I will keep this idea for later.
