### ISSUE TITLE
So many issues ...

### ISSUE THREAD

**Issue by A-nglea** [clitic/vsd#7]

**Comment by A-nglea** [comment]
Needed to add quotes around the files in this line:-
ffmpeg -i '(video) manifest.m4s' -i '(audio) manifest.m4s' -i '(subtitles) manifest.vtt' -c:v copy -c:a copy -scodec mov_text -metadata:s:a:0 language=en -metadata:s:s:0 language=en -disposition:s:0 default testing.mp4

--key KID:KEY failed when using multiple keys:
vsd save https://vod.rte.ie/rte/vod-d/RTE_Prod_-_Prod/643/456/IP10001223-16-0001/M3781788-1672832705164.ism/.mpd --key 4f5079a17425c68606a268fdc274d83f:082d81ce42efca5e6e18a6658003ad43 --key 82009a402f4a51879ff204969cd737ef:e0656bafeeb2d36739fae712690f8908 --key 53695e21e9f65524a2090a982783b3bc:871ab244f1aac44dd34c1eda5eca8f6d --key b438e49b5e7d57099e5a6a177a6c955d:39dbfa38c66dcdd4ca2d6d895faf3a6f --key 5400c17faeab57d0a724a9db5a080487:a8abfdc433457172ee221e9c4e9a7e53  -t 1 -o irish.mp4
with:-
Encrypted CENC streams found in playlist
error: use --key flag to specify CENC decryption keys for the following kid(s): 4F5079A1-7425-C686-06A2-68FDC274D83F

Always fails with segmentation fault if threads any more than 1

Is this now dead?

**Comment by A-nglea** [comment]
My subtiltes file as downlaoded is saved as '(subtitles) manifest.txt'
The ffmpeg lines references a (subtitles) manifest.vtt 
These are simple to catch errors why am I seeing them?

**Comment by clitic** [comment]
@A-nglea

> Needed to add quotes around the files in this line:-

That is not required, ffmpeg process is called correctly internally. Eventually I will remove space character.

> My subtiltes file as downlaoded is saved as '(subtitles) manifest.txt' The ffmpeg lines references a '(subtitles) manifest.vtt'

I will fix this error.

> Always fails with segmentation fault if threads any more than 1

I have found the solution to resolve this bug and I will fix it soon.

I will fix all issues and notify you soon.

**Comment by clitic** [comment]
@A-nglea See [Changelog.md](https://github.com/clitic/vsd/blob/main/CHANGELOG.md)
